### ISSUE TITLE
pytest-xdist interop: signal only works in main thread

### ISSUE THREAD

**Issue by pytest-timeout-bot** [pytest-dev/pytest-timeout#8]
**[Original report](https://bitbucket.org/pytest-dev/pytest-timeout/issue/8) by Buck Evan (Bitbucket: [bukzor](https://bitbucket.org/bukzor), GitHub: [bukzor](https://github.com/bukzor)).**

----------------------------------------

I'm getting this kind of error with increasing frequency as I add tests to my project.

```
#!python

INTERNALERROR>   File "/home/travis/build/Yelp/venv-update/.tox/test/lib/python3.4/site-packages/_pytest/main.py", line 84, in wrap_session
INTERNALERROR>     doit(config, session)
INTERNALERROR>   File "/home/travis/build/Yelp/venv-update/.tox/test/lib/python3.4/site-packages/_pytest/main.py", line 122, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/travis/build/Yelp/venv-update/.tox/test/lib/python3.4/site-packages/_pytest/core.py", line 413, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/home/travis/build/Yelp/venv-update/.tox/test/lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/home/travis/build/Yelp/venv-update/.tox/test/lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "<remote exec>", line 59, in pytest_runtestloop
INTERNALERROR>   File "<remote exec>", line 72, in run_tests
INTERNALERROR>   File "/home/travis/build/Yelp/venv-update/.tox/test/lib/python3.4/site-packages/_pytest/core.py", line 413, in __call__
INTERNALERROR>     return self._docall(methods, kwargs)
INTERNALERROR>   File "/home/travis/build/Yelp/venv-update/.tox/test/lib/python3.4/site-packages/_pytest/core.py", line 424, in _docall
INTERNALERROR>     res = mc.execute()
INTERNALERROR>   File "/home/travis/build/Yelp/venv-update/.tox/test/lib/python3.4/site-packages/_pytest/core.py", line 315, in execute
INTERNALERROR>     res = method(**kwargs)
INTERNALERROR>   File "/home/travis/build/Yelp/venv-update/.tox/test/lib/python3.4/site-packages/pytest_timeout.py", line 70, in pytest_runtest_protocol
INTERNALERROR>     timeout_setup(item)
INTERNALERROR>   File "/home/travis/build/Yelp/venv-update/.tox/test/lib/python3.4/site-packages/pytest_timeout.py", line 95, in timeout_setup
INTERNALERROR>     signal.signal(signal.SIGALRM, handler)
INTERNALERROR> ValueError: signal only works in main thread
```

Full detail:

 * http://paste.pound-python.org/show/qnK7qab1vZEYbYIzwLXD/
 * http://paste.pound-python.org/show/5SnhQMlELjJgiE3Lwpim/

**Comment by lucrib** [comment]
Any news about this?
I am facing this issue.
I am trying to gather new logs for this.

**Comment by lucrib** [comment]
Not sure if this will help or not, but I found some python bugs related to this:
https://bugs.python.org/issue38904
https://bugs.python.org/issue39042
Also this thread on stack overflow.
https://stackoverflow.com/questions/54749342/valueerror-signal-only-works-in-main-thread

I don't have knowledge enough to figure out how to fix this, but if someone could give me some direction I could try to submit a PR for this.

**Comment by uniqueni** [comment]
I am facing this issue too
and I have no workaround 
please

**Comment by flub** [comment]
I've re-read this whole thread again.  Most of these complaints seem to me like some other environments which are making pytest run in not the main thread and/or other signal handling from the application interfering.  I'm going to close this again as I don't think this is overly useful currently.

**Comment by mchlnix** [comment]
I encountered this problem also with the combination of a CI, xdist and timeout. Signals crashed regularly and threads made the test run stuck at 100%.

So in the script my CI worker was executing, I set xdist to use all, but one core. This left one core/thread idle, which I hoped could be used by the OS for whatever, thus ensuring, that all the test-runners are undisturbed and can all claim their own main thread.

It has worked so far.

For linux: `CPU_COUNT="$(grep -c "^processor" /proc/cpuinfo)"` so `pytest - n $(( CPU_COUNT - 1 ))`

**Comment by ndevenish** [comment]
I know this is an old thread, and appreciate the unhelpfulness of "me too" reports, but we just ran into this several-CI-runs-in-a-row, with basically the same stacktrace as the original (Jenkins on `platform linux -- Python 3.8.6, pytest-6.2.1, py-1.10.0, pluggy-0.13.1/; plugins: dials-data-2.1.36, timeout-1.4.2, xdist-2.2.0, mock-3.5.1, forked-1.2.0`).

If it's just happening for tests that have timed out then it's not much of a problem, it would have failed anyway. But the stacktrace looks like it's a problem _registering_ the handler, rather than executing it?

I seem to be able to quite reliably reproduce with a clean environment via Docker:
```dockerfile
from ubuntu:latest

RUN apt update && apt install -y python3 python3-pip && pip3 install pytest pytest-xdist pytest-timeout
RUN printf '\
from time import sleep\n\
import pytest\n\
@pytest.mark.timeout(10000)\n\
@pytest.mark.parametrize("value", range(0, 20))\n\
def test_timeout(value):\n\
    sleep(5)\n\
    pass' >> t.py
RUN echo "set -e; while true; do pytest t.py -v -n20; done" > dotest.sh
```
This seems to reproduce it pretty reliably, every time:
```
$ docker build -t testtimeout .
$ docker run -it testtimeout bash dotest.sh
....
INTERNALERROR> E             ValueError: signal only works in main thread
INTERNALERROR> E           assert False
```
Where `-n` >> number of cores (my docker VM on this machine only has one core allocated to it). I wonder, if it's something to do with long time spent collecting?

**Comment by ndevenish** [comment]
Some more notes:
- `pytest t.py -v -n20` on it's own seems to trigger the problem ~80% of the time
- I cannot get this to reproduce _without_ `-v` verbose mode - removing `-v` and it happily runs over and over, at least as long as I tried
- I inserted this code in before the `signal.signal` line:
```python
pathlib.Path(f"{os.getpid()}-{threading.current_thread().ident}.log").write_text(f"""
{"GOOD" if threading.current_thread() == threading.main_thread() else "BAD"}
{threading.current_thread().ident=}
{threading.main_thread().ident=}
{os.getpid()=}
{"".join(traceback.format_stack())}
""")
```
and the tracebacks are identical for good & bad _except_ the bad instances don't have the stack before `_perform_spawn` e.g.:
```
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "/usr/local/lib/python3.8/dist-packages/execnet/gateway_base.py", line 1554, in serve
    SlaveGateway(io=io, id=id, _startcount=2).serve()
  File "/usr/local/lib/python3.8/dist-packages/execnet/gateway_base.py", line 1060, in serve
    self._execpool.integrate_as_primary_thread()
  File "/usr/local/lib/python3.8/dist-packages/execnet/gateway_base.py", line 267, in integrate_as_primary_thread
    self._perform_spawn(reply)

^^^^ Traceback above here does not appear on "BAD" runs where thread != main_thread

  File "/usr/local/lib/python3.8/dist-packages/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
  File "/usr/local/lib/python3.8/dist-packages/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/execnet/gateway_base.py", line 1084, in executetask
    do_exec(co, loc)  # noqa
....
  File "/usr/local/lib/python3.8/dist-packages/pytest_timeout.py", line 104, in pytest_runtest_protocol
    timeout_setup(item)
  File "/usr/local/lib/python3.8/dist-packages/pytest_timeout.py", line 213, in timeout_setup
    {"".join(traceback.format_stack())}
```
which, reading https://github.com/pytest-dev/execnet/blob/master/execnet/gateway_base.py#L267 - seems to indicate that sometimes this is called explicitly as a primary thread, and in some combination of cases I'm not yet certain on, execnet spawns a worker as a non-primary-thread.

I'm not sure yet if this is a problem with `pytest-timeout`'s assumption that it's called on _a_ main thread, or whether there is some race-condition bug in execnet/pytest-xdist

**Comment by ndevenish** [comment]
So, https://github.com/ndevenish/pytest-timeout/commit/bf39d0a68053f6ef3fcaa90a4ee5c248862af1c6 fixes this issue, in the most trivial way - it falls back to `thread` mode if it detects that signal is going to fail. I'm not sure the full balance of choice between thread and signal, I've read in https://github.com/postlund/pyatv/issues/904 that thread mode has an increased risk of hanging - but hopefully since it'd only be falling back to thread mode in the corner cases, I think this is a small enough risk for my use cases.

If this was the route to take - and I suspect it's significantly simpler than finding the cause in xdist/execnet - then maybe a third "auto" mode (or debug "signalwithfallback") could be added and explicitly used by the people who seem to be running into this more often.

I'm not sure if this thread is monitored so if not, I'll make a PR to start the conversation at some point.

**Comment by flub** [comment]
Hi @ndevenish, thanks for the explorations and additional info!  The commit you point to is very interesting indeed.  I'm a bit surprised that with xdist threaded mode can hang, I that'd be interesting to understand better as well.

Certainly do take this to a PR, at first glance I'm a bit torn on automatically switching to threaded vs just erroring out and forcing someone to decide this explicitly.  But it would be nice to improve usability somehow and you found a pretty promising way I think.

(also, apologies I'm not always the most active, responses can take a while as you just noticed)

**Comment by ndevenish** [comment]
> (also, apologies I'm not always the most active, responses can take a while as you just noticed)

I have no expectations for reply times for open source projects! I'll try to pull a PR together, for discussion if nothing else.

**Comment by graingert** [comment]
@flub this should be fixed (mostly) on execnet==1.8.0

**Comment by ndevenish** [comment]
Ah, that's good to hear. I was settling on "Error, but with a more helpful suggestion" as the least-worst way to "fix", and didn't want to dig into execnet. Evidently it annoyed someone further than it annoyed me :)

**Comment by flub** [comment]
@graingert oh, that's very nice work you did!  Might finally fix this issue properly and would mean we don't need a workaround here.

**Comment by pseudotensor** [comment]
Yes, we've gotten ever since using xdist + timeout together.  It's fairly random:

```
Still get this on 2.2.0 xdist:

```
internal error
def worker_internal_error(self, node, formatted_error):
        """
        pytest_internalerror() was called on the worker.
    
        pytest_internalerror() arguments are an excinfo and an excrepr, which can't
        be serialized, so we go with a poor man's solution of raising an exception
        here ourselves using the formatted message.
        """
        self._active_nodes.remove(node)
        try:
>           assert False, formatted_error
E           AssertionError: Traceback (most recent call last):
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/_pytest/main.py", line 257, in wrap_session
E                 session.exitstatus = doit(config, session) or 0
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/_pytest/main.py", line 313, in _main
E                 config.hook.pytest_runtestloop(session=session)
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
E                 return self._hookexec(self, self.get_hookimpls(), kwargs)
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
E                 return self._inner_hookexec(hook, methods, kwargs)
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
E                 self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
E                 return outcome.get_result()
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
E                 raise ex[1].with_traceback(ex[2])
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
E                 res = hook_impl.function(*args)
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/xdist/remote.py", line 75, in pytest_runtestloop
E                 self.run_one_test(torun)
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/xdist/remote.py", line 89, in run_one_test
E                 self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
E                 return self._hookexec(self, self.get_hookimpls(), kwargs)
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
E                 return self._inner_hookexec(hook, methods, kwargs)
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
E                 self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
E                 return outcome.get_result()
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
E                 raise ex[1].with_traceback(ex[2])
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/pluggy/callers.py", line 182, in _multicall
E                 next(gen)  # first yield
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/pytest_timeout.py", line 104, in pytest_runtest_protocol
E                 timeout_setup(item)
E               File "/opt/h2oai/dai/python/lib/python3.8/site-packages/pytest_timeout.py", line 207, in timeout_setup
E                 signal.signal(signal.SIGALRM, handler)
E               File "/opt/h2oai/dai/python/lib/python3.8/signal.py", line 47, in signal
E                 handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
E             ValueError: signal only works in main thread
E           assert False

/opt/h2oai/dai/python/lib/python3.8/site-packages/xdist/dsession.py:187: AssertionError
```


```

**Comment by xoviat** [comment]
@flub Can you close this?

**Comment by flub** [comment]
I guess so, pytest-timeout now recognises this situation and will refuse to use the signal timeout method, falling back to the thread method.
